In [ ]:
from asg_expense_tracker.jio_payments_bank_reader import JioPaymentsBankReader
import pandas as pd

jio_df = JioPaymentsBankReader(pdf_path="asg_expense_tracker/stored_files/00272171124045613-Sep-2025 15_53_33.pdf").df
sept_expenses = jio_df[(jio_df.Date.dt.month == 9) & (jio_df.Date.dt.year == 2025)]

In [11]:
sept_expenses.head()

,Date,Transaction_Type,Direction,Transaction_ID,Merchant,Bank_Code,UPI_VPA,Comments,Withdrawal,Deposit,Balance
42,2025-09-01,UPI,DEBIT,524457744993,ETERNAL LIMITED,AIRPzomatoonli,ZomatoOn,None,222.06,0.00,36855.49
43,2025-09-01,UPI,DEBIT,524463664981,ZOMATO LIMITED,HDFC,zomatofd.p,UPIInten,272.61,0.00,36582.88
44,2025-09-02,UPI,DEBIT,524579210971,NETPLUS BROADBAND,HDFC,netplusbro,Paid via,706.82,0.00,35876.06
45,2025-09-02,UPI,CREDIT,524532166079,supermoney,YESB,supermoney,Supermon,0.00,10.91,35886.97
46,2025-09-02,UPI,DEBIT,524528553790,Amazon Pay Balance,RATN,amazonpayb,Request,1000.00,0.00,34886.97